"""initial_schema

Revision ID: 0c37a26b60ab
Revises: 
Create Date: 2025-09-28 22:18:32.650527

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '0c37a26b60ab'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('articles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('website', sa.String(length=255), nullable=False),
    sa.Column('headline', sa.String(length=500), nullable=False),
    sa.Column('published_at', sa.DateTime(), nullable=True),
    sa.Column('parsed_at', sa.DateTime(), nullable=False),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('content', sa.Text(), nullable=True),
    sa.Column('language', sa.String(length=10), nullable=True),
    sa.Column('link', sa.String(length=1000), nullable=False),
    sa.Column('content_hash', sa.String(length=32), nullable=True),
    sa.Column('feed_name', sa.String(length=255), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_category_country', 'articles', ['category', 'country'], unique=False)
    op.create_index('idx_published_language', 'articles', ['published_at', 'language'], unique=False)
    op.create_index('idx_website_published', 'articles', ['website', 'published_at'], unique=False)
    op.create_index(op.f('ix_articles_category'), 'articles', ['category'], unique=False)
    op.create_index(op.f('ix_articles_content_hash'), 'articles', ['content_hash'], unique=True)
    op.create_index(op.f('ix_articles_country'), 'articles', ['country'], unique=False)
    op.create_index(op.f('ix_articles_feed_name'), 'articles', ['feed_name'], unique=False)
    op.create_index(op.f('ix_articles_id'), 'articles', ['id'], unique=False)
    op.create_index(op.f('ix_articles_language'), 'articles', ['language'], unique=False)
    op.create_index(op.f('ix_articles_published_at'), 'articles', ['published_at'], unique=False)
    op.create_index(op.f('ix_articles_website'), 'articles', ['website'], unique=False)
    op.create_table('daily_summaries',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.DateTime(), nullable=False),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('country', sa.String(length=10), nullable=True),
    sa.Column('text_summary', sa.Text(), nullable=False),
    sa.Column('articles_count', sa.Integer(), nullable=False),
    sa.Column('generated_at', sa.DateTime(), nullable=False),
    sa.Column('model_name', sa.String(length=50), nullable=False),
    sa.Column('main_events', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('key_themes', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('detailed_summary', sa.Text(), nullable=True),
    sa.Column('impacted_regions', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('timeline', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('raw_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('error_count', sa.Integer(), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_daily_summaries_impacted_regions', 'daily_summaries', ['impacted_regions'], unique=False, postgresql_using='gin')
    op.create_index('idx_daily_summaries_key_themes', 'daily_summaries', ['key_themes'], unique=False, postgresql_using='gin')
    op.create_index('idx_daily_summaries_main_events', 'daily_summaries', ['main_events'], unique=False, postgresql_using='gin')
    op.create_index('idx_date_category_country', 'daily_summaries', ['date', 'category', 'country'], unique=True)
    op.create_index(op.f('ix_daily_summaries_category'), 'daily_summaries', ['category'], unique=False)
    op.create_index(op.f('ix_daily_summaries_country'), 'daily_summaries', ['country'], unique=False)
    op.create_index(op.f('ix_daily_summaries_date'), 'daily_summaries', ['date'], unique=False)
    op.create_index(op.f('ix_daily_summaries_id'), 'daily_summaries', ['id'], unique=False)
    op.create_table('feed_status',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('feed_name', sa.String(length=255), nullable=False),
    sa.Column('feed_url', sa.String(length=1000), nullable=False),
    sa.Column('last_parsed_at', sa.DateTime(), nullable=True),
    sa.Column('last_success_at', sa.DateTime(), nullable=True),
    sa.Column('articles_count', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('feed_name')
    )
    op.create_index(op.f('ix_feed_status_id'), 'feed_status', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_feed_status_id'), table_name='feed_status')
    op.drop_table('feed_status')
    op.drop_index(op.f('ix_daily_summaries_id'), table_name='daily_summaries')
    op.drop_index(op.f('ix_daily_summaries_date'), table_name='daily_summaries')
    op.drop_index(op.f('ix_daily_summaries_country'), table_name='daily_summaries')
    op.drop_index(op.f('ix_daily_summaries_category'), table_name='daily_summaries')
    op.drop_index('idx_date_category_country', table_name='daily_summaries')
    op.drop_index('idx_daily_summaries_main_events', table_name='daily_summaries', postgresql_using='gin')
    op.drop_index('idx_daily_summaries_key_themes', table_name='daily_summaries', postgresql_using='gin')
    op.drop_index('idx_daily_summaries_impacted_regions', table_name='daily_summaries', postgresql_using='gin')
    op.drop_table('daily_summaries')
    op.drop_index(op.f('ix_articles_website'), table_name='articles')
    op.drop_index(op.f('ix_articles_published_at'), table_name='articles')
    op.drop_index(op.f('ix_articles_language'), table_name='articles')
    op.drop_index(op.f('ix_articles_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_feed_name'), table_name='articles')
    op.drop_index(op.f('ix_articles_country'), table_name='articles')
    op.drop_index(op.f('ix_articles_content_hash'), table_name='articles')
    op.drop_index(op.f('ix_articles_category'), table_name='articles')
    op.drop_index('idx_website_published', table_name='articles')
    op.drop_index('idx_published_language', table_name='articles')
    op.drop_index('idx_category_country', table_name='articles')
    op.drop_table('articles')
    # ### end Alembic commands ###
