"""create_grok_interactions_table

Revision ID: b37c483e185a
Revises: 9ebc95ca31d0
Create Date: 2025-09-28 22:21:11.856450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "b37c483e185a"
down_revision: Union[str, Sequence[str], None] = "9ebc95ca31d0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("books")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "books",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("title", sa.VARCHAR(length=255), autoincrement=False, nullable=False),
        sa.Column("author", sa.VARCHAR(length=255), autoincrement=False, nullable=True),
        sa.Column("publication_year", sa.INTEGER(), autoincrement=False, nullable=True),
        sa.Column(
            "in_stock",
            sa.BOOLEAN(),
            server_default=sa.text("true"),
            autoincrement=False,
            nullable=True,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("books_pkey")),
    )
    # ### end Alembic commands ###
