"""add_top_articles_column

Revision ID: d4c8e2f1a3b9
Revises: b37c483e185a
Create Date: 2025-11-29 10:00:00.000000

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "d4c8e2f1a3b9"
down_revision: Union[str, Sequence[str], None] = "b37c483e185a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "daily_summaries",
        sa.Column("top_articles", postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("daily_summaries", "top_articles")
    # ### end Alembic commands ###
