name: RSS Parser

on:
  schedule:
    - cron: "0 */4 * * *"  # Every 4 hours
  workflow_dispatch:

jobs:
  parse:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install UV
        run: |
          pip install uv

      - name: Install dependencies
        run: |
          uv sync

      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$GITHUB_WORKSPACE" >> $GITHUB_ENV

      - name: Run RSS Parser
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: uv run parser/rss_parser.py
