name: Scheduled Tasks

on:
  schedule:
    - cron: "0 */4 * * *"  # Every 4 hours
    - cron: "0 0 * * *"    # Once per day at midnight

jobs:
  run-tasks:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          uv install

      - name: Run RSS Parser
        if: ${{ github.event.schedule == '0 */4 * * *' }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
        run: uv run parser/rss_parser.py

      - name: Run Summarization
        if: ${{ github.event.schedule == '0 0 * * *' }}
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
          XAI_API_KEY: ${{ secrets.XAI_API_KEY }}
        run: uv run summarizers/daily_processor.py